apiVersion: batch/v1
kind: Job
metadata:
  name: secret-copy-job
  namespace: {{ .Values.demo.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops    
spec:
  template:
    spec:
      serviceAccountName: pipelines
      containers:
      - name: secret-copy
        image: registry.redhat.io/openshift4/ose-cli
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        command:
        - /bin/sh
        - -c
        - |
          GITLAB_TOKEN=$(oc get secret secrets-rhdh -n rhdh-operator -o jsonpath='{.data.GITLAB_TOKEN}' | base64 --decode)
          WEBHOOK_PAT=$(oc get secret secrets-rhdh -n rhdh-operator -o jsonpath='{.data.GITLAB_WEBHOOK_SECRET}' | base64 --decode)
          oc create secret generic {{ .Values.demo.componentid }}-git-token --from-literal=token=$GITLAB_TOKEN
          oc create secret generic {{ .Values.demo.componentid }}-webhook-secret --from-literal=secret=$WEBHOOK_PAT
          oc create secret docker-registry {{ .Values.demo.componentid }}-push-secret --docker-username=$(oc whoami) --docker-password=$(oc whoami -t) --docker-email=test@acme.com --docker-server=image-registry.openshift-image-registry.svc:5000
      restartPolicy: Never
  backoffLimit: 1
