apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: kaniko-test-pipeline
  namespace: mytest2
spec:
  finally:
    - name: kaniko-test-pipeline
      params:
        - name: IMAGE
          value: 'image-registry.openshift-image-registry.svc:5000/mytest2/tesy:latest'
        - name: DOCKERFILE
          value: ./Dockerfile
        - name: CONTEXT
          value: ./
        - name: EXTRA_ARGS
          value: []
        - name: BUILDER_IMAGE
          value: 'gcr.io/kaniko-project/executor:v1.5.1@sha256:c6166717f7fe0b7da44908c986137ecfeab21f31ec3992f6e128fff8a94be8a5'
      taskRef:
        kind: Task
        name: kaniko-test-task
      workspaces:
        - name: source
          workspace: my-working-source
        - name: dockerconfig
          workspace: credencial
  tasks:
    - name: git-clone
      params:
        - name: CRT_FILENAME
          value: ca-bundle.crt
        - name: HTTP_PROXY
          value: ''
        - name: HTTPS_PROXY
          value: ''
        - name: NO_PROXY
          value: ''
        - name: SUBDIRECTORY
          value: ''
        - name: USER_HOME
          value: /home/git
        - name: DELETE_EXISTING
          value: 'true'
        - name: VERBOSE
          value: 'false'
        - name: SSL_VERIFY
          value: 'false'
        - name: URL
          value: 'https://github.com/sgutierr/simplestdockerfile.git'
        - name: REVISION
          value: main
        - name: REFSPEC
          value: ''
        - name: SUBMODULES
          value: 'true'
        - name: DEPTH
          value: '1'
        - name: SPARSE_CHECKOUT_DIRECTORIES
          value: ''
      taskRef:
        params:
          - name: kind
            value: task
          - name: name
            value: git-clone
          - name: namespace
            value: openshift-pipelines
        resolver: cluster
      workspaces:
        - name: output
          workspace: my-working-source
  workspaces:
    - name: my-working-source
    - name: credencial