apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: buildah-pipelinerun
  namespace: {{ .Values.demo.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "4"    
  finalizers:
    - chains.tekton.dev/pipelinerun
    - results.tekton.dev/pipelinerun
spec:
  pipelineRef:
    name: buildah-pipeline
  taskRunTemplate:
    serviceAccountName: builder
  timeouts:
    pipeline: 1h0m0s
  workspaces:
    - name: source-folder
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
          storageClassName: managed-nfs-storage
          volumeMode: Filesystem