apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    openshift.io/description: buildah-demo
    openshift.io/display-name: buildah-demo
  name: buildah-demo