apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: buildah-demo-app
  namespace: openshift-gitops
  labels:
    argocd/app-name: buildah-demo-app
  annotations:
    argocd/app-name: buildah-demo-app
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: buildah-demo
  project: default
  source:
    path: deployment/
    repoURL: 'https://github.com/sgutierr/buildah-demo.git'
    targetRevision: HEAD
  helm:
    valueFiles:
      - values.yaml    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 10m
      limit: 10
    syncOptions:
      - CreateNamespace=true