apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: buildah-piperun
  namespace: {{ .Values.demo.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"    
  finalizers:
    - chains.tekton.dev/pipelinerun
    - results.tekton.dev/pipelinerun
spec:
  pipelineRef:
    name: buildah-pipeline
  taskRunTemplate:
    serviceAccountName: pipelines-sa-userid-1000
  timeouts:
    pipeline: 1h0m0s
  workspaces:
    - name: source-folder
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
          storageClassName: managed-nfs-storage
          volumeMode: Filesystem
    - name: dockerconfig
      secret:
        items:
          - key: .dockerconfigjson
            path: auth.json
        secretName: {{ .Values.demo.component-id }}-push-secret